name: Build the a project NODE JS
on: push
jobs: 
    test:
        runs-on: ubuntu-latest
        steps: 
            - name: Get code
              uses: action/checkout@04            
            - name: Install Node JS
              uses: action/setup-node@04
              with:
                node-version: 18         

